// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
      case TargetPlatform.android:
       return android;
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBANGbYNw71tMvJcNgYeHcryKXJmTEhLhI',
    appId: '1:640220038337:web:b5cb3456084ae07cf94040',
    messagingSenderId: '640220038337',
    projectId: 'rrt1-60802',
    authDomain: 'rrt1-60802.firebaseapp.com',
    storageBucket: 'rrt1-60802.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALj8O9Wb_L3vHxjaxi5w3PK7NJN1bCNqs',
    appId: '1:640220038337:android:3f7455470d986f7af94040',
    messagingSenderId: '640220038337',
    projectId: 'rrt1-60802',
    storageBucket: 'rrt1-60802.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr3rrFpipXssjvAvSvYN1o7avbX3PhyeI',
    appId: '1:640220038337:ios:64036e980aa55406f94040',
    messagingSenderId: '640220038337',
    projectId: 'rrt1-60802',
    storageBucket: 'rrt1-60802.appspot.com',
    iosClientId: '640220038337-8jpnca9a51fn69pnjinatukuln9ovjhf.apps.googleusercontent.com',
    iosBundleId: 'com.flutterflow.healthai',
  );
}
